
title = "udp server 配置文件"
# 监听端口
port = 8888
# 日志存储地址
log_dir = "/tmp"

[reader]
#时间间隔重新生成文件 单位:分 60min
interval = 60
# 读取缓冲区大小 byte
read_buffer = 1048576

#发送服务器配置
[sender]
# 是否启用sender 默认不启用
enabled = false
# channel缓存
channel_size = 50000

[[sender.remote_server]]
protocol = "tcp"
ip = "127.0.0.1"
port = 8080
# 是否启用连接池 tcp有效
pool_enabled = true
# 连接池配置
[sender.remote_server.conn_pool]
# 初始化连接数
initial_cap = 30
# 最大连接数
max_cap = 50
# 连接失效时间
idle_timeout = 10


[[sender.remote_server]]
protocol = "udp"
ip = "127.0.0.1"
port = 8080
